export interface RegistarskoPodrucje {
  id: number;
  oznaka: string;
  grad: string;
}


export const REGISTARSKA_PODRUCJA: RegistarskoPodrucje[] = [
  { id: 1, oznaka: 'AC', grad: 'Aleksandrovac' },
  { id: 2, oznaka: 'AL', grad: 'Aleksinac' },
  { id: 3, oznaka: 'AR', grad: 'Aranđelovac' },
  { id: 4, oznaka: 'BB', grad: 'Bajina Bašta' },
  { id: 5, oznaka: 'BG', grad: 'Beograd' },
  { id: 6, oznaka: 'BO', grad: 'Bor' },
  { id: 7, oznaka: 'BP', grad: 'Bačka Palanka' },
  { id: 8, oznaka: 'BT', grad: 'Bačka Topola' },
  { id: 9, oznaka: 'BU', grad: 'Bujanovac' },
  { id: 10, oznaka: 'BĆ', grad: 'Bogatić' },
  { id: 11, oznaka: 'BČ', grad: 'Bečej' },
  { id: 12, oznaka: 'DE', grad: 'Despotovac' },
  { id: 13, oznaka: 'GL', grad: 'Gnjilane' },
  { id: 14, oznaka: 'GM', grad: 'Gornji Milanovac' },
  { id: 15, oznaka: 'IC', grad: 'Ivanjica' },
  { id: 16, oznaka: 'IN', grad: 'Inđija' },
  { id: 17, oznaka: 'JA', grad: 'Jagodina' },
  { id: 18, oznaka: 'KA', grad: 'Kanjiža' },
  { id: 19, oznaka: 'KC', grad: 'Koceljeva' },
  { id: 20, oznaka: 'KG', grad: 'Kragujevac' },
  { id: 21, oznaka: 'KI', grad: 'Kikinda' },
  { id: 22, oznaka: 'KL', grad: 'Kladovo' },
  { id: 23, oznaka: 'KM', grad: 'Kosovska Mitrovica' },
  { id: 24, oznaka: 'KO', grad: 'Kovin' },
  { id: 25, oznaka: 'KV', grad: 'Kraljevo' },
  { id: 26, oznaka: 'KŠ', grad: 'Kruševac' },
  { id: 27, oznaka: 'KŽ', grad: 'Knjaževac' },
  { id: 28, oznaka: 'LB', grad: 'Lebane' },
  { id: 29, oznaka: 'LE', grad: 'Leskovac' },
  { id: 30, oznaka: 'LO', grad: 'Loznica' },
  { id: 31, oznaka: 'LU', grad: 'Lučani' },
  { id: 32, oznaka: 'NG', grad: 'Negotin' },
  { id: 33, oznaka: 'NI', grad: 'Niš' },
  { id: 34, oznaka: 'NP', grad: 'Novi Pazar' },
  { id: 35, oznaka: 'NS', grad: 'Novi Sad' },
  { id: 36, oznaka: 'NV', grad: 'Nova Varoš' },
  { id: 37, oznaka: 'PA', grad: 'Pančevo' },
  { id: 38, oznaka: 'PB', grad: 'Priboj' },
  { id: 39, oznaka: 'PE', grad: 'Peć' },
  { id: 40, oznaka: 'PI', grad: 'Pirot' },
  { id: 41, oznaka: 'PK', grad: 'Prokuplje' },
  { id: 42, oznaka: 'PN', grad: 'Paraćin' },
  { id: 43, oznaka: 'PO', grad: 'Požarevac' },
  { id: 44, oznaka: 'PP', grad: 'Prijepolje' },
  { id: 45, oznaka: 'PR', grad: 'Priština' },
  { id: 46, oznaka: 'PT', grad: 'Petrovac' },
  { id: 47, oznaka: 'PZ', grad: 'Prizren' },
  { id: 48, oznaka: 'PŽ', grad: 'Požega' },
  { id: 49, oznaka: 'RA', grad: 'Raška' },
  { id: 50, oznaka: 'RU', grad: 'Ruma' },
  { id: 51, oznaka: 'SA', grad: 'Senta' },
  { id: 52, oznaka: 'SC', grad: 'Surdulica' },
  { id: 53, oznaka: 'SD', grad: 'Smederevo' },
  { id: 54, oznaka: 'SJ', grad: 'Sjenica' },
  { id: 55, oznaka: 'SM', grad: 'Sremska Mitrovica' },
  { id: 56, oznaka: 'SO', grad: 'Sombor' },
  { id: 57, oznaka: 'SP', grad: 'Smederevska Palanka' },
  { id: 58, oznaka: 'ST', grad: 'Stara Pazova' },
  { id: 59, oznaka: 'SU', grad: 'Subotica' },
  { id: 60, oznaka: 'SV', grad: 'Svijalnac' },
  { id: 61, oznaka: 'TO', grad: 'Topola' },
  { id: 62, oznaka: 'TS', grad: 'Trstenik' },
  { id: 63, oznaka: 'TT', grad: 'Tutin' },
  { id: 64, oznaka: 'UB', grad: 'Ub' },
  { id: 65, oznaka: 'UE', grad: 'Užice' },
  { id: 66, oznaka: 'UR', grad: 'Uroševac' },
  { id: 67, oznaka: 'VA', grad: 'Valjevo' },
  { id: 68, oznaka: 'VB', grad: 'Vrnjačka Banja' },
  { id: 69, oznaka: 'VL', grad: 'Vlasotince' },
  { id: 70, oznaka: 'VP', grad: 'Velika Plana' },
  { id: 71, oznaka: 'VR', grad: 'Vranje' },
  { id: 72, oznaka: 'VS', grad: 'Vrbas' },
  { id: 73, oznaka: 'VŠ', grad: 'Vršac' },
  { id: 74, oznaka: 'ZA', grad: 'Zaječar' },
  { id: 75, oznaka: 'ZR', grad: 'Zrenjanin' },
  { id: 76, oznaka: 'ĆU', grad: 'Ćuprija' },
  { id: 77, oznaka: 'ČA', grad: 'Čačak' },
  { id: 78, oznaka: 'ĐA', grad: 'Đakovica' },
  { id: 79, oznaka: 'ŠA', grad: 'Šabac' },
  { id: 80, oznaka: 'ŠI', grad: 'Šid' },
];
